name: drift_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.16.0
  get: ^4.6.6
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0
  json_annotation: ^4.8.1
  uuid: ^4.3.3
  collection: ^1.18.0
  log_me: ^0.1.2
  mutex: ^3.1.0
  sqlite3: ^2.4.2
  drift_dev: ^2.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  build_web_compilers:
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
