builders:
  drift_generator:
    import: "package:drift_generator/src/generator.dart"
    builder_factories: [ "driftBuilder" ]
    build_extensions: { ".dart": [ ".drift.g.dart" ] }
    auto_apply: dependents
    build_to: source
    runs_before: [ "drift_dev" ]